.equ	t_out_key1 =0x60
.equ	t_out_key2 =0x61

.equ	code_keylo =0x63
.equ	code_keyhi =0x64

.equ	code_templo =0x65
.equ	code_temphi =0x66

.equ	code_waterlo =0x67
.equ	code_waterhi =0x68

.equ	mv_templo =0x69
.equ	mv_temphi =0x6a
.equ	mv_temp_remains =0x6b

.equ	tem_seg_h1 =0x6c
.equ	tem_seg_h2 =0x6d
.equ	tem_seg_h3 =0x6e


.equ	menu_seg_h1_r =0x6f
.equ	menu_seg_h2_r =0x70
.equ	menu_seg_h3_r =0x71

.equ	menu_seg_h1 =0x72
.equ	menu_seg_h2 =0x73
.equ	menu_seg_h3 =0x74

.equ	counter_power_off =0x75;

.equ	beep_pause =0x76;

.equ	fareng_tem =0x77

.equ	const_water =0x78

.equ	const_v_ref_hi =0x79
.equ	const_v_ref_lo =0x7a


.equ	counter_adc	=0x7b

.equ	code_templo_temp =0x7c
.equ	code_temphi_temp =0x7d

.equ	corr0_temp =0x7e

.equ	key_pause_activ =0x7f

.equ	wait3s_lo =0x80
.equ	wait3s_hi =0x81

.equ	dev_log =0x83

.equ	wait_menu_out_time_lo =0x84
.equ	wait_menu_out_time_hi =0x85

.equ	code_battery =0x86